version: "3.1"
services:

 db:
   container_name: db_postgres
   image: postgres:12.1
   volumes:
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: postgres

 car-app:
   container_name: car_app_backend
   image: car-app
   ports:
     - "8080:8080"
     - "4848:4848"
     - "8181:8181"
   volumes:
     - ../target/car.war:/opt/payara41/deployments/car.war